### ISSUE TITLE
chore: Sidekiq test suite fails to start redis when one is already running

### ISSUE THREAD

**Issue by arielvalentin** [open-telemetry/opentelemetry-ruby#1165]
Most test suites rely on users executing tests using the docker-compose managed services in local development and Action managed services in CI. 

The sidekiq test suite attempts to start a redis server during tests with specific configurations and if you are running redis via `docker-compose` or as part of Actions CI it results in a backtrace but the test suite passes: 

```console
@arielvalentin ➜ /workspaces/opentelemetry-ruby/instrumentation/sidekiq (use-gem-versions) $ bundle exec appraisal sidekiq-6.3 rake test
>> BUNDLE_GEMFILE=/workspaces/opentelemetry-ruby/instrumentation/sidekiq/gemfiles/sidekiq_6.3.gemfile bundle exec rake test
Traceback (most recent call last):
        43: from /home/codespace/.ruby/current/bin/bundle:23:in `<main>'
        42: from /home/codespace/.ruby/current/bin/bundle:23:in `load'
        41: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.5/exe/bundle:36:in `<top (required)>'
        40: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.5/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        39: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.5/exe/bundle:48:in `block in <top (required)>'
        38: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.5/lib/bundler/cli.rb:25:in `start'
        37: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        36: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.5/lib/bundler/cli.rb:31:in `dispatch'
        35: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        34: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        33: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        32: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.5/lib/bundler/cli.rb:484:in `exec'
        31: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.5/lib/bundler/cli/exec.rb:23:in `run'
        30: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.5/lib/bundler/cli/exec.rb:58:in `kernel_load'
        29: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.5/lib/bundler/cli/exec.rb:58:in `load'
        28: from /home/codespace/.ruby/current/bin/rake:23:in `<top (required)>'
        27: from /home/codespace/.ruby/current/bin/rake:23:in `load'
        26: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
        25: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
        24: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
        23: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
        22: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
        21: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
        20: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
        19: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
        18: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
        17: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
        16: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
        15: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
        14: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
        13: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
        12: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
        11: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
        10: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
         9: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
         8: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
         7: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
         6: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
         5: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
         4: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
         3: from /workspaces/opentelemetry-ruby/instrumentation/sidekiq/Rakefile:15:in `block in <top (required)>'
         2: from /workspaces/opentelemetry-ruby/instrumentation/sidekiq/Rakefile:15:in `fork'
         1: from /workspaces/opentelemetry-ruby/instrumentation/sidekiq/Rakefile:15:in `block (2 levels) in <top (required)>'
/workspaces/opentelemetry-ruby/instrumentation/sidekiq/Rakefile:15:in `exec': No such file or directory - redis-server (Errno::ENOENT)
2022-03-28T14:28:31.938Z pid=12109 tid=7mp INFO: Booting Sidekiq 6.4.1 with redis options {:password=>"REDACTED", :url=>"redis://127.0.0.1:16379/0"}
Run options: --seed 45071

# Running:

.......................................

Finished in 6.324330s, 6.1667 runs/s, 18.1837 assertions/s.

39 runs, 115 assertions, 0 failures, 0 errors, 0 skips
```

We should change the Sidekiq test suite to behave the same way as the rest of the tests.

**Comment by jonatas** [comment]
It seems like the version used in the example is not available in the main branch.
Trying to reproduce it here:

```
 BUNDLE_GEMFILE=/Users/jonatasdp/code/opentelemetry-ruby/instrumentation/sidekiq/gemfiles/sidekiq_6.3.gemfile bundle exec rake test
/Users/jonatasdp/code/opentelemetry-ruby/instrumentation/sidekiq/gemfiles/sidekiq_6.3.gemfile not found```

Using other versions it works fine. I patched my local version to see what it looks like in the CI but I'm not sure if the implementation is the way to go:

```diff
--- instrumentation/sidekiq/Rakefile
+++ instrumentation/sidekiq/Rakefile
@@ -12,7 +12,9 @@ require 'rubocop/rake_task'
 RuboCop::RakeTask.new

 task :start_redis do
-  @redis_pid = fork { exec 'redis-server test/redis.conf' }
+  if `which redis-server`.lines.any?
+    @redis_pid = fork { exec 'redis-server test/redis.conf' }
+  end
 end
```

**Comment by arielvalentin** [comment]
@jonatas Thanks for looking into it!

None of the other test suites manage instances of their services and all rely on the host managed or running docker containers so I personally lean towards removing launching redis from rake.

@fhwang @fbogsany Do you all agree? Looking at this PR it seems like you all were keen on having the test suite manage the redis server lifecycle https://github.com/open-telemetry/opentelemetry-ruby/pull/713

**Comment by fhwang** [comment]
Personally I don't have a strong opinion either way, though being consistent with the other test suites seems like it'd be less confusing overall.

**Comment by fbogsany** [comment]
I'm keen for developers running tests locally to *NOT* have to remember to start and stop the dependent services. However we accomplish that is fine with me - I just want a standard way to run tests locally for any of our gems (and for all of our gems) that "does all the things" in a reproducible way.

The README prior to #713 said:

> ## Development
> 
> You'll need Redis installed locally to run the test suite. Once you've
> installed it, start it with the included configuration:
> 
> ```
> redis-server test/redis.conf
> ```

I don't want to return to this state.

The other thing that PR added was use of a non-standard port, to avoid conflicts if a developer was running Redis locally for some reason.

**Comment by arielvalentin** [comment]
I would assert most folks doing development on apps that use external dependencies like Redis and MySQL don't expect their test suite to manage instances of those environments but maybe my sample size is too small.

I am sympathetic to that being inconvenient for folks but I am in favor of having contributors using the provided docker-compose managed services.

I do recognize that using docker-compose won't solve the friction in cases that the instrumented gems have platform specific bindings.
Contributors will need to install dependencies for those and I don't think we'll be able to provide sufficient bootstrap scripts to get their dev environment setup. 

All that being said, I will go with the group on this.

**Comment by jonatas** [comment]
I don't know if it was discussed previously but anyone has thought about introducing a [hermit config](https://github.com/cashapp/hermit) to activate the right tooling and related versions in an isolated environment?
