### ISSUE TITLE
PG Instrumentation SystemStackError on Rails 5.2.5 Ruby 2.6.3

### ISSUE THREAD

**Issue by nvolker** [open-telemetry/opentelemetry-ruby#1178]
**Description of the bug**

When enabling the PG instrumentation in one of our older Rails 5, PG applications, I encounter the following **SystemStackError** exception (expand example below). From what I can tell, the setup is successful but when trying to write spans the exception is encountered.

_I will continue to debug on my end and update the issue if I find the root cause._

**Share details about your runtime**

Operating system details: `MacOS Catalina, 10.15.7`
RAILS_VERSION: `5.2.5`
RUBY_ENGINE: `ruby`
RUBY_VERSION: `2.6.3`
RUBY_DESCRIPTION: `ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]`
PostgreSQL Info:
```shell
➜  my_app git:(master) ✗ psql --version
psql (PostgreSQL) 14.2
➜  my_app git:(master) ✗ brew info postgresql
postgresql: stable 14.2 (bottled), HEAD
Object-relational database system
https://www.postgresql.org/
/usr/local/Cellar/postgresql/14.2 (3,305 files, 45.5MB) *
  Poured from bottle on 2022-02-24 at 18:24:14
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/postgresql.rb
License: PostgreSQL
==> Dependencies
Build: pkg-config ✔
Required: icu4c ✘, krb5 ✘, openssl@1.1 ✘, readline ✔
```

**Share a simplified reproduction if possible**

<details>
  <summary>Working Configuration without PG instrumentation</summary>
  
  ```ruby
    OpenTelemetry::SDK.configure do |c|
      c.service_name = service_name
      c.logger = Rails.logger
    
      c.use "OpenTelemetry::Instrumentation::ActiveJob"
      c.use "OpenTelemetry::Instrumentation::ActionPack"
      c.use "OpenTelemetry::Instrumentation::ActiveRecord"
      c.use "OpenTelemetry::Instrumentation::ActiveSupport"
      c.use "OpenTelemetry::Instrumentation::ActionView"
      c.use "OpenTelemetry::Instrumentation::Rails"
    end
  ```

  Server startup output (`rails s`):
  ```console
  ➜  my_app git:(master) ✗ rails s
  => Booting Puma
  => Rails 5.2.5 application starting in development
  => Run `rails server -h` for more startup options
  DEBUG Upgrading default proxy tracer provider to OpenTelemetry::SDK::Trace::TracerProvider
  INFO Instrumentation: OpenTelemetry::Instrumentation::ActiveJob was successfully installed
  INFO Instrumentation: OpenTelemetry::Instrumentation::ActionPack was successfully installed
  INFO Instrumentation: OpenTelemetry::Instrumentation::ActiveRecord was successfully installed
  INFO Instrumentation: OpenTelemetry::Instrumentation::ActiveSupport was successfully installed
  INFO Instrumentation: OpenTelemetry::Instrumentation::ActionView was successfully installed
  INFO Instrumentation: OpenTelemetry::Instrumentation::Rails was successfully installed
  Puma starting in single mode...
  * Version 3.12.4 (ruby 2.6.3-p62), codename: Llamas in Pajamas
  * Min threads: 5, max threads: 5
  * Environment: development
  * Listening on tcp://localhost:1234
  Use Ctrl-C to stop
  ```
</details>

<details>
  <summary>Broken Configuration with PG instrumentation</summary>
  
  ```ruby
    OpenTelemetry::SDK.configure do |c|
      c.service_name = service_name
      c.logger = Rails.logger
    
      c.use "OpenTelemetry::Instrumentation::ActiveJob"
      c.use "OpenTelemetry::Instrumentation::ActionPack"
      c.use "OpenTelemetry::Instrumentation::ActiveRecord"
      c.use "OpenTelemetry::Instrumentation::ActiveSupport"
      c.use "OpenTelemetry::Instrumentation::ActionView"
      c.use "OpenTelemetry::Instrumentation::PG" # only addition from the working example
      c.use "OpenTelemetry::Instrumentation::Rails"
    end
  ```

  Server startup output (`rails s`):
  ```console
  ➜  my_app git:(master) ✗ rails s
  => Booting Puma
  => Rails 5.2.5 application starting in development
  => Run `rails server -h` for more startup options
  DEBUG Upgrading default proxy tracer provider to OpenTelemetry::SDK::Trace::TracerProvider
  INFO Instrumentation: OpenTelemetry::Instrumentation::ActiveJob was successfully installed
  INFO Instrumentation: OpenTelemetry::Instrumentation::ActionPack was successfully installed
  INFO Instrumentation: OpenTelemetry::Instrumentation::ActiveRecord was successfully installed
  INFO Instrumentation: OpenTelemetry::Instrumentation::ActiveSupport was successfully installed
  INFO Instrumentation: OpenTelemetry::Instrumentation::ActionView was successfully installed
  INFO Instrumentation: OpenTelemetry::Instrumentation::PG was successfully installed
  INFO Instrumentation: OpenTelemetry::Instrumentation::Rails was successfully installed
  Exiting
  Traceback (most recent call last):
	  9542: from bin/rails:4:in `<main>'
	  9541: from bin/rails:4:in `require'
	  9540: from /Users/user/.rvm/gems/ruby-2.6.3/gems/railties-5.2.5/lib/rails/commands.rb:18:in `<top (required)>'
	  9539: from /Users/user/.rvm/gems/ruby-2.6.3/gems/railties-5.2.5/lib/rails/command.rb:46:in `invoke'
	  9538: from /Users/user/.rvm/gems/ruby-2.6.3/gems/railties-5.2.5/lib/rails/command/base.rb:69:in `perform'
	  9537: from /Users/user/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	  9536: from /Users/user/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	  9535: from /Users/user/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	   ... 9530 levels...
	     4: from /Users/user/.rvm/gems/ruby-2.6.3/gems/opentelemetry-instrumentation-pg-0.19.2/lib/opentelemetry/instrumentation/pg/patches/connection.rb:126:in `database_name'
	     3: from /Users/user/.rvm/gems/ruby-2.6.3/gems/pg-1.2.3/lib/pg/connection.rb:248:in `conninfo_hash'
	     2: from /Users/user/.rvm/gems/ruby-2.6.3/gems/pg-1.2.3/lib/pg/connection.rb:248:in `each_with_object'
	     1: from /Users/user/.rvm/gems/ruby-2.6.3/gems/pg-1.2.3/lib/pg/connection.rb:248:in `each'
  /Users/user/.rvm/gems/ruby-2.6.3/gems/pg-1.2.3/lib/pg/connection.rb:249:in `block in conninfo_hash': stack level too deep (SystemStackError)
  ```
</details>

<details>
  <summary>Some additional debugger info</summary>

  I set the tracer output to console (`ENV["OTEL_TRACES_EXPORTER"] = "console"`) and got several thousand spans that look like this:

  ```console
    #<struct OpenTelemetry::SDK::Trace::SpanData
    name="SET my_app_development",
    kind=:client,
    status=
    #<OpenTelemetry::Trace::Status:0x00007fd8f910cd70
      @code=2,
      @description="Unhandled exception of type: SystemStackError">,
    parent_span_id="\x00\x00\x00\x00\x00\x00\x00\x00",
    total_recorded_attributes=8,
    total_recorded_events=1,
    total_recorded_links=0,
    start_timestamp=1649669447025724000,
    end_timestamp=1649669450223932000,
    attributes=
    {"db.system"=>"postgresql",
      "db.user"=>"user",
      "db.name"=>"my_app_development",
      "net.peer.name"=>"127.0.0.1",
      "net.transport"=>"IP.TCP",
      "net.peer.port"=>"5432",
      "db.operation"=>"SET",
      "db.statement"=>"SET client_min_messages TO ?"},
    links=nil,
    events=
    [#<struct OpenTelemetry::SDK::Trace::Event
      name="exception",
      attributes=
        {"exception.type"=>"SystemStackError",
        "exception.message"=>"stack level too deep",
        "exception.stacktrace"=>
          "/Users/user/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/pp.rb:161:in `block in pp': stack level too deep (SystemStackError)\n" +
          "\tfrom /Users/user/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/prettyprint.rb:253:in `block (2 levels) in group'\n" +
          "\tfrom /Users/user/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/prettyprint.rb:280:in `nest'\n" +
          "\tfrom /Users/user/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/prettyprint.rb:252:in `block in group'\n" +
          "\tfrom /Users/user/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/prettyprint.rb:265:in `group_sub'\n" +
          "\tfrom /Users/user/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/prettyprint.rb:251:in `group'\n" +
          "\tfrom /Users/user/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/pp.rb:161:in `pp'\n" +
          "\tfrom /Users/user/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/pp.rb:399:in `block (2 levels) in pretty_print'\n" +
          "\tfrom /Users/user/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/pp.rb:224:in `block in seplist'\n" +
          "\t ... 9548 levels...\n" +
          "\tfrom /Users/user/.rvm/gems/ruby-2.6.3/gems/railties-5.2.5/lib/rails/command.rb:46:in `invoke'\n" +
          "\tfrom /Users/user/.rvm/gems/ruby-2.6.3/gems/railties-5.2.5/lib/rails/commands.rb:18:in `<top (required)>'\n" +
          "\tfrom bin/rails:4:in `require'\n" +
          "\tfrom bin/rails:4:in `<main>'\n"},
      timestamp=1649669450223909000>],
    resource=
    #<OpenTelemetry::SDK::Resources::Resource:0x00007fd91e688fe0
      @attributes=
      {"service.name"=>"my_app",
        "process.pid"=>44203,
        "process.command"=>"bin/rails",
        "process.runtime.name"=>"ruby",
        "process.runtime.version"=>"2.6.3",
        "process.runtime.description"=>
        "ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]",
        "telemetry.sdk.name"=>"opentelemetry",
        "telemetry.sdk.language"=>"ruby",
        "telemetry.sdk.version"=>"1.0.2"}>,
    instrumentation_library=
    #<struct OpenTelemetry::SDK::InstrumentationLibrary
      name="OpenTelemetry::Instrumentation::PG",
      version="0.19.2">,
    span_id="b\xDF\r\xA2\x95\xC6I\x82",
    trace_id="z\xE8\xF2[\xAC\xA6[z\x16\xE1\xC7\xD3NN\xBBu",
    trace_flags=#<OpenTelemetry::Trace::TraceFlags:0x00007fd98d5793d8 @flags=1>,
    tracestate=#<OpenTelemetry::Trace::Tracestate:0x00007fd96d5956e8 @hash={}>>
  Exiting
  Traceback (most recent call last):
    9560: from bin/rails:4:in `<main>'
    9559: from bin/rails:4:in `require'
    9558: from /Users/user/.rvm/gems/ruby-2.6.3/gems/railties-5.2.5/lib/rails/commands.rb:18:in `<top (required)>'
    9557: from /Users/user/.rvm/gems/ruby-2.6.3/gems/railties-5.2.5/lib/rails/command.rb:46:in `invoke'
    9556: from /Users/user/.rvm/gems/ruby-2.6.3/gems/railties-5.2.5/lib/rails/command/base.rb:69:in `perform'
    9555: from /Users/user/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
    9554: from /Users/user/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
    9553: from /Users/user/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
      ... 9548 levels...
        4: from /Users/user/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/prettyprint.rb:265:in `group_sub'
        3: from /Users/user/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/prettyprint.rb:252:in `block in group'
        2: from /Users/user/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/prettyprint.rb:280:in `nest'
        1: from /Users/user/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/prettyprint.rb:253:in `block (2 levels) in group'
  /Users/user/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/pp.rb:161:in `block in pp': stack level too deep (SystemStackError)
  ```

>

**Comment by nvolker** [comment]
Found the issue.

For this particular application, we have `rack-mini-profiler (2.0.2)` installed and enabled for development mode. This gem patches PG in a way that conflicts with the [PG instrumentation](https://github.com/open-telemetry/opentelemetry-ruby/blob/37f39224d48bcee5d085ad88da1be5cb22b63c68/instrumentation/pg/lib/opentelemetry/instrumentation/pg.rb) causing [this method](https://github.com/MiniProfiler/rack-mini-profiler/blob/v2.0.2/lib/patches/db/pg.rb#L109) to get stuck in an infinite loop.

<details>
  <summary>For additional context, the OTEL gem versions installed are as follows:</summary>

  ```
      opentelemetry-api (1.0.1)
      opentelemetry-common (0.19.3)
        opentelemetry-api (~> 1.0)
      opentelemetry-exporter-otlp (0.21.2)
        google-protobuf (~> 3.7)
        opentelemetry-api (~> 1.0)
        opentelemetry-common (~> 0.19.3)
        opentelemetry-sdk (~> 1.0)
      opentelemetry-instrumentation-action_pack (0.1.3)
        opentelemetry-api (~> 1.0)
        opentelemetry-instrumentation-base (~> 0.19.0)
        opentelemetry-instrumentation-rack (~> 0.20.0)
      opentelemetry-instrumentation-action_view (0.2.0)
        opentelemetry-api (~> 1.0.0)
        opentelemetry-instrumentation-active_support (~> 0.1.0)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-active_job (0.1.5)
        opentelemetry-api (~> 1.0)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-active_model_serializers (0.18.4)
        opentelemetry-api (~> 1.0)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-active_record (0.2.2)
        opentelemetry-api (~> 1.0)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-active_support (0.1.1)
        opentelemetry-api (~> 1.0)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-all (0.23.0)
        opentelemetry-instrumentation-action_pack (~> 0.1.3)
        opentelemetry-instrumentation-action_view (~> 0.2.0)
        opentelemetry-instrumentation-active_job (~> 0.1.4)
        opentelemetry-instrumentation-active_model_serializers (~> 0.18.3)
        opentelemetry-instrumentation-active_record (~> 0.2.1)
        opentelemetry-instrumentation-active_support (~> 0.1.0)
        opentelemetry-instrumentation-aws_sdk (~> 0.2.0)
        opentelemetry-instrumentation-bunny (~> 0.18.3)
        opentelemetry-instrumentation-concurrent_ruby (~> 0.19.1)
        opentelemetry-instrumentation-dalli (~> 0.20.0)
        opentelemetry-instrumentation-delayed_job (~> 0.18.3)
        opentelemetry-instrumentation-ethon (~> 0.19.2)
        opentelemetry-instrumentation-excon (~> 0.19.2)
        opentelemetry-instrumentation-faraday (~> 0.19.2)
        opentelemetry-instrumentation-graphql (~> 0.19.1)
        opentelemetry-instrumentation-http (~> 0.19.2)
        opentelemetry-instrumentation-http_client (~> 0.19.2)
        opentelemetry-instrumentation-koala (~> 0.18.3)
        opentelemetry-instrumentation-lmdb (~> 0.19.1)
        opentelemetry-instrumentation-mongo (~> 0.18.3)
        opentelemetry-instrumentation-mysql2 (~> 0.20.0)
        opentelemetry-instrumentation-net_http (~> 0.19.2)
        opentelemetry-instrumentation-pg (~> 0.19.1)
        opentelemetry-instrumentation-que (~> 0.2.0)
        opentelemetry-instrumentation-rack (~> 0.20.0)
        opentelemetry-instrumentation-rails (~> 0.20.0)
        opentelemetry-instrumentation-redis (~> 0.21.1)
        opentelemetry-instrumentation-resque (~> 0.1.2)
        opentelemetry-instrumentation-restclient (~> 0.19.2)
        opentelemetry-instrumentation-ruby_kafka (~> 0.18.4)
        opentelemetry-instrumentation-sidekiq (~> 0.20.1)
        opentelemetry-instrumentation-sinatra (~> 0.19.2)
        opentelemetry-instrumentation-trilogy (~> 0.50.0)
      opentelemetry-instrumentation-aws_sdk (0.2.2)
        opentelemetry-api (~> 1.0)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-base (0.19.0)
        opentelemetry-api (~> 1.0)
      opentelemetry-instrumentation-bunny (0.18.4)
        opentelemetry-api (~> 1.0)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-concurrent_ruby (0.19.2)
        opentelemetry-api (~> 1.0)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-dalli (0.20.0)
        opentelemetry-api (~> 1.0)
        opentelemetry-common (~> 0.19.3)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-delayed_job (0.18.4)
        opentelemetry-api (~> 1.0)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-ethon (0.19.4)
        opentelemetry-api (~> 1.0)
        opentelemetry-common (~> 0.19.3)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-excon (0.19.4)
        opentelemetry-api (~> 1.0)
        opentelemetry-common (~> 0.19.3)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-faraday (0.19.3)
        opentelemetry-api (~> 1.0)
        opentelemetry-common (~> 0.19.3)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-graphql (0.19.2)
        opentelemetry-api (~> 1.0)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-http (0.19.4)
        opentelemetry-api (~> 1.0)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-http_client (0.19.4)
        opentelemetry-api (~> 1.0)
        opentelemetry-common (~> 0.19.3)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-koala (0.18.4)
        opentelemetry-api (~> 1.0)
        opentelemetry-common (~> 0.19.3)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-lmdb (0.19.2)
        opentelemetry-api (~> 1.0)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-mongo (0.18.4)
        opentelemetry-api (~> 1.0)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-mysql2 (0.20.0)
        opentelemetry-api (~> 1.0)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-net_http (0.19.4)
        opentelemetry-api (~> 1.0)
        opentelemetry-common (~> 0.19.3)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-pg (0.19.2)
        opentelemetry-api (~> 1.0)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-que (0.2.0)
        opentelemetry-api (~> 1.0)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-rack (0.20.1)
        opentelemetry-api (~> 1.0)
        opentelemetry-common (~> 0.19.3)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-rails (0.20.0)
        opentelemetry-api (~> 1.0)
        opentelemetry-instrumentation-action_pack (~> 0.1.3)
        opentelemetry-instrumentation-action_view (~> 0.2.0)
        opentelemetry-instrumentation-active_record (~> 0.2.2)
        opentelemetry-instrumentation-active_support (~> 0.1.0)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-redis (0.21.3)
        opentelemetry-api (~> 1.0)
        opentelemetry-common (~> 0.19.3)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-resque (0.1.3)
        opentelemetry-api (~> 1.0)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-restclient (0.19.3)
        opentelemetry-api (~> 1.0)
        opentelemetry-common (~> 0.19.3)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-ruby_kafka (0.18.5)
        opentelemetry-api (~> 1.0)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-sidekiq (0.20.2)
        opentelemetry-api (~> 1.0)
        opentelemetry-common (~> 0.19.3)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-sinatra (0.19.3)
        opentelemetry-api (~> 1.0)
        opentelemetry-common (~> 0.19.3)
        opentelemetry-instrumentation-base (~> 0.19.0)
      opentelemetry-instrumentation-trilogy (0.50.1)
        opentelemetry-api (~> 1.0)
        opentelemetry-instrumentation-base (~> 0.19.0)
        opentelemetry-semantic_conventions (>= 1.8.0)
      opentelemetry-sdk (1.0.2)
        opentelemetry-api (~> 1.0)
        opentelemetry-common (~> 0.19.3)
        opentelemetry-instrumentation-base (~> 0.19.0)
        opentelemetry-semantic_conventions
      opentelemetry-semantic_conventions (1.8.0)
        opentelemetry-api (~> 1.0)
  ```
</details>

**Comment by orangewolf** [comment]
Had a similar issue - mine turned out to be use of the PrometheusExporter. Changing

```ruby
Rails.application.middleware.unshift PrometheusExporter::Middleware
```

to

```ruby
Rails.application.middleware.use PrometheusExporter::Middleware
```

fixed it for me (aka it was a load order issue)

Ideally we wouldnt need both but OpenTel Ruby isn't quite there yet.
