### ISSUE TITLE
batch_span_processor spans list may contains something else than spans ?

### ISSUE THREAD

**Issue by kedare** [open-telemetry/opentelemetry-ruby#1418]
**Description of the bug**

We had a case when running a quite big rake tasks, the batch_span_processor would crash the application with the following error.

```ruby
rake aborted!
back_1       | NoMethodError: undefined method `to_span_data' for [#<OpenTelemetry::SDK::Trace::Span..........] # Very long list
back_1       | 
back_1       |               batch = snapshot.shift(@batch_size).map!(&:to_span_data)
back_1       |                                                  ^^^^^
back_1       | /usr/local/bundle/gems/opentelemetry-sdk-1.2.0/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb:113:in `map!'
back_1       | /usr/local/bundle/gems/opentelemetry-sdk-1.2.0/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb:113:in `force_flush'
back_1       | /usr/local/bundle/gems/opentelemetry-sdk-1.2.0/lib/opentelemetry/sdk/trace/tracer_provider.rb:109:in `block (2 levels) in force_flush'
back_1       | /usr/local/bundle/gems/opentelemetry-sdk-1.2.0/lib/opentelemetry/sdk/trace/tracer_provider.rb:105:in `map'
back_1       | /usr/local/bundle/gems/opentelemetry-sdk-1.2.0/lib/opentelemetry/sdk/trace/tracer_provider.rb:105:in `block in force_flush'
back_1       | /usr/local/bundle/gems/opentelemetry-sdk-1.2.0/lib/opentelemetry/sdk/trace/tracer_provider.rb:101:in `synchronize'
back_1       | /usr/local/bundle/gems/opentelemetry-sdk-1.2.0/lib/opentelemetry/sdk/trace/tracer_provider.rb:101:in `force_flush'
back_1       | /usr/local/bundle/gems/opentelemetry-instrumentation-rake-0.1.0/lib/opentelemetry/instrumentation/rake/patches/task.rb:32:in `force_flush'
back_1       | /usr/local/bundle/gems/opentelemetry-instrumentation-rake-0.1.0/lib/opentelemetry/instrumentation/rake/patches/task.rb:14:in `invoke'
back_1       | /usr/local/bundle/gems/bundler-2.3.17/lib/bundler/cli/exec.rb:58:in `load'
back_1       | /usr/local/bundle/gems/bundler-2.3.17/lib/bundler/cli/exec.rb:58:in `kernel_load'
back_1       | /usr/local/bundle/gems/bundler-2.3.17/lib/bundler/cli/exec.rb:23:in `run'
back_1       | /usr/local/bundle/gems/bundler-2.3.17/lib/bundler/cli.rb:483:in `exec'
back_1       | /usr/local/bundle/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
back_1       | /usr/local/bundle/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
back_1       | /usr/local/bundle/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
back_1       | /usr/local/bundle/gems/bundler-2.3.17/lib/bundler/cli.rb:31:in `dispatch'
back_1       | /usr/local/bundle/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
back_1       | /usr/local/bundle/gems/bundler-2.3.17/lib/bundler/cli.rb:25:in `start'
back_1       | /usr/local/bundle/gems/bundler-2.3.17/exe/bundle:48:in `block in <top (required)>'
back_1       | /usr/local/bundle/gems/bundler-2.3.17/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
back_1       | /usr/local/bundle/gems/bundler-2.3.17/exe/bundle:36:in `<top (required)>'
back_1       | /usr/local/bundle/bin/bundle:25:in `load'
back_1       | /usr/local/bundle/bin/bundle:25:in `<main>'
```

Somehow it looks like one of the integration is inserting something else than a span in the batch ?

**Share details about your runtime**

Operating system details: Linux, Ubuntu 20.04 LTS
RUBY_ENGINE: "ruby"
RUBY_VERSION: "3.1.2"
RUBY_DESCRIPTION: "ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]"

Integrations configuration

```
service_name = ENV.fetch('OTEL_SERVICE_NAME', 'back')

OpenTelemetry::SDK.configure do |c|
  c.service_name = service_name

  # Rails
  c.use "OpenTelemetry::Instrumentation::Rack"
  c.use "OpenTelemetry::Instrumentation::Rails"
  c.use "OpenTelemetry::Instrumentation::Rake"
  c.use "OpenTelemetry::Instrumentation::ActiveSupport"
  c.use "OpenTelemetry::Instrumentation::ActionPack"
  c.use "OpenTelemetry::Instrumentation::ActiveJob"
  c.use "OpenTelemetry::Instrumentation::ActiveRecord"
  c.use "OpenTelemetry::Instrumentation::ActionView"

  # Network libraries
  c.use "OpenTelemetry::Instrumentation::ConcurrentRuby"
  c.use "OpenTelemetry::Instrumentation::Faraday"
  c.use "OpenTelemetry::Instrumentation::Net::HTTP"

  # Storage
  c.use "OpenTelemetry::Instrumentation::AwsSdk"

  # Database and queues
  c.use "OpenTelemetry::Instrumentation::PG"
  c.use "OpenTelemetry::Instrumentation::Rdkafka"
  c.use "OpenTelemetry::Instrumentation::Redis"

  # Worker
  c.use "OpenTelemetry::Instrumentation::Sidekiq", {
    propagation_style: :child
  }
end

AppTracer = OpenTelemetry.tracer_provider.tracer(service_name)
```

**Share a simplified reproduction if possible**

Still investigating on how to reproduce it in a small setup, not sure I will find this.

**Comment by kedare** [comment]
I suspect it's coming from the rake integration, removing it make the error go away (I will do more test, not sure if it's related to this or if it's just random)

**Comment by kedare** [comment]
I can confirm I can reproduce this issue as soon as I run my rake tasks with the rake integration active, disabling `OpenTelemetry::Instrumentation::Rake` prevents this issue (but then I lose the integration features), so the issue is probably related to this integration.
Maybe there should be done kind of safeguard in the way the core library accept spans to prevent this ?

**Comment by arielvalentin** [comment]
Would you mind sharing the list of items that are _not_ of type SDK spans? 

E.g. do you see API spans or nil entries in that list?

**Comment by kedare** [comment]
What would be the easiest way to extract the list items ?
I only get the very long line from the logs but it doesn't looks like it's easily parseable into something usable

**Comment by arielvalentin** [comment]
Are you able to reproduce it in a development environment?

**Comment by kedare** [comment]
I can reproduce it in our CI, I will check if I can also reproduce it locally (it did not happen during my local tests)

**Comment by plantfansam** [comment]
If it's in CI, you could monkey-patch `OpenTelemetry::SDK::Trace::Export::BatchSpanProcessor#[force_flush](https://github.com/open-telemetry/opentelemetry-ruby/blob/fcecf418eb67804c1bc6b1dfdf9ca71949f2f40f/sdk/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb#L103)` to log something. e.g.
 
```ruby
module OpenTelemetry
  module SDK
    module Trace
      module Export
        # Implementation of the duck type SpanProcessor that batches spans
        # exported by the SDK then pushes them to the exporter pipeline.
        #
        # Typically, the BatchSpanProcessor will be more suitable for
        # production environments than the SimpleSpanProcessor.
        #
        # All spans reported by the SDK implementation are first added to a
        # synchronized queue (with a {max_queue_size} maximum size, after the
        # size is reached spans are dropped) and exported every
        # schedule_delay to the exporter pipeline in batches of
        # max_export_batch_size.
        #
        # If the queue gets half full a preemptive notification is sent to the
        # worker thread that exports the spans to wake up and start a new
        # export cycle.
        class BatchSpanProcessor # rubocop:disable Metrics/ClassLength
          def force_flush
                        start_time = OpenTelemetry::Common::Utilities.timeout_timestamp
            snapshot = lock do
              reset_on_fork if @keep_running
              spans.shift(spans.size)
            end
            until snapshot.empty?
              remaining_timeout = OpenTelemetry::Common::Utilities.maybe_timeout(timeout, start_time)
              return TIMEOUT if remaining_timeout&.zero?
              batch = snapshot.shift(@batch_size)
              #### NEW STUFF HERE
              batch_classes = batch.map{ |i| i.class }.uniq
              OpenTelemetry.logger.warn(batch_classes.join(", ")) if batch_classes.length > 1  
              batch = batch.map!(&:to_span_data)
              #### END NEW STUFF
              result_code = export_batch(batch, timeout: remaining_timeout)
              return result_code unless result_code == SUCCESS
            end

            @exporter.force_flush(timeout: OpenTelemetry::Common::Utilities.maybe_timeout(timeout, start_time))
          ensure
            # Unshift the remaining spans if we timed out. We drop excess spans from
            # the snapshot because they're older than any spans in the spans buffer.
            lock do
              n = spans.size + snapshot.size - max_queue_size
              if n.positive?
                snapshot.shift(n)
                report_dropped_spans(n, reason: 'buffer-full')
              end
              spans.unshift(snapshot) unless snapshot.empty?
              @condition.signal if spans.size > max_queue_size / 2
            end
          end
        end
      end
    end
end
```

**Comment by kedare** [comment]
Sorry for the delay,

This is what I get from the logs (Also I had to add the missing timeout parameter to `force_flush` method)

```json
{"level":"WARN","timestamp":"2023-01-18T13:06:26.900+00:00","logger.method_name":"cardiologs.open_telemetry","message":"Array, OpenTelemetry::SDK::Trace::Span"}
```

Somehow an array gets in ?
I will try to extract the content when the array is detected

**Comment by kedare** [comment]
More investigation focusing on the rake task. I do see a strange behaviour, the same Rake task `fake_data` is showing 2 different spans, one in the batch and one in the array in the batch, same rake task but different span, I don't think this is supposed to happen ?

I would expect a single span per rake task ?

```ruby
def scan_array(given_array, level: 1, max_level: 20)
  throw Exception.new("Too many levels") if level > max_level

  batch_classes = given_array.map { |i| i.class }.uniq
  prefix = "SPAN-DUMP:" + ("-" * level)
  puts("#{prefix}: #{given_array.length} #{batch_classes}")
  arrays = given_array.filter {|e| e.class == Array}
  spans_types = given_array.filter { |e| e.class == OpenTelemetry::SDK::Trace::Span }.map{ |e| e.instrumentation_scope.name }.tally
  spans2 = []
  given_array.each do |span|
    if span.class == OpenTelemetry::SDK::Trace::Span
      name = span.instrumentation_scope.name
      if name == "OpenTelemetry::Instrumentation::Rake"
        task = span.attributes["rake.task"]
        span_id = Digest::MD5.hexdigest span.context.span_id
        name = "#{name}-#{task}-#{span_id}"
      end
      spans2.append(name)
    end
  end
  spans2.each do |span|
    puts("#{prefix}: #{span}")
  end
  arrays.each {|e| scan_array(e, level: level+1)}
  return
end
```

```bash
docker-compose -f cypress/jenkins.docker-compose.yml logs back | grep SPAN-DUMP | grep Rake
cypress-back-1  | SPAN-DUMP:-: OpenTelemetry::Instrumentation::Rake-db:load_config-825e0dc7ec7f58edd17d3ba7755d3644
cypress-back-1  | SPAN-DUMP:-: OpenTelemetry::Instrumentation::Rake-db:create-3379ba89b123e0b6c2c0f8eee0576ce2
cypress-back-1  | SPAN-DUMP:-: OpenTelemetry::Instrumentation::Rake-db:check_protected_environments-d5f4ae00d38af468ec3b3225ffb4446c
cypress-back-1  | SPAN-DUMP:-: OpenTelemetry::Instrumentation::Rake-db:schema:load-0c8b315b5150f13ea90a87005d8aa5dc
cypress-back-1  | SPAN-DUMP:-: OpenTelemetry::Instrumentation::Rake-db:schema:load-914dde8eadb256963a18886ca80d9902
cypress-back-1  | SPAN-DUMP:-: OpenTelemetry::Instrumentation::Rake-setup_db:fake_data-7bf08c23f2af83dee3c66a3bcaeccaff
cypress-back-1  | SPAN-DUMP:--: OpenTelemetry::Instrumentation::Rake-setup_db:fake_data-82f3afc91db7e41f4bed63152d347ec5
```

**Comment by kedare** [comment]
Ok I got a reproducible scenario (not isolated from my codebase but it should be easy to isolate)

Make sure you don't have any exporter configured but SDK enabled

To reproduce, create a rake task that spams span

```ruby
namespace :lab do
  task spam_spans: :environment do
    2000.times do |i|
      AppTracer.in_span("boom") do
      end
    end
  end
end
```

(Here I use my global AppTracer but you can probably create one just for it)

If you run the rake task alone with `rake lab:spam_spans`,  it works fine. (You will just get a timeout and warning at the end saying it could not export the span, which is expected)

If you run the multiple task in a single rake call, it will fail : `rake lab:spam_spans lab:spam_spans lab:spam_spans`

**Comment by kedare** [comment]
Let me know if you have issues reproducing it
