### ISSUE TITLE
"stack level too deep" on redis trace

### ISSUE THREAD

**Issue by treyhyde** [open-telemetry/opentelemetry-ruby#579]
Rails 6 / unicorn application with `c.use_all`

This happens with and without prometheus instrumentation enabled.  So may or may not be related to open-telemetry/opentelemetry-ruby#352

```
/app/vendor/bundle/ruby/2.6.0/gems/opentelemetry-api-0.12.1/lib/opentelemetry/context.rb:110:in `value': stack level too deep (SystemStackError)
	from /app/vendor/bundle/ruby/2.6.0/gems/opentelemetry-api-0.12.1/lib/opentelemetry/trace.rb:62:in `current_span'
	from /app/vendor/bundle/ruby/2.6.0/gems/opentelemetry-sdk-0.12.1/lib/opentelemetry/sdk/trace/samplers/constant_sampler.rb:30:in `should_sample?'
	from /app/vendor/bundle/ruby/2.6.0/gems/opentelemetry-sdk-0.12.1/lib/opentelemetry/sdk/trace/samplers/parent_based.rb:56:in `should_sample?'
	from /app/vendor/bundle/ruby/2.6.0/gems/opentelemetry-sdk-0.12.1/lib/opentelemetry/sdk/trace/tracer.rb:47:in `start_span'
	from /app/vendor/bundle/ruby/2.6.0/gems/opentelemetry-api-0.12.1/lib/opentelemetry/trace/tracer.rb:28:in `in_span'
	from /app/vendor/bundle/ruby/2.6.0/gems/opentelemetry-instrumentation-redis-0.12.0/lib/opentelemetry/instrumentation/redis/patches/client.rb:18:in `call'
	from (eval):9:in `call'
	from /app/vendor/bundle/ruby/2.6.0/gems/opentelemetry-instrumentation-redis-0.12.0/lib/opentelemetry/instrumentation/redis/patches/client.rb:23:in `block in call'
	 ... 9346 levels...
	from /app/vendor/bundle/ruby/2.6.0/bin/unicorn:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/unicorn:23:in `<main>'
	from /app/vendor/bundle/ruby/2.6.0/bin/ruby_executable_hooks:24:in `eval'
	from /app/vendor/bundle/ruby/2.6.0/bin/ruby_executable_hooks:24:in `<main>'
```

<img width="988" alt="Screen Shot 2021-01-26 at 3 43 14 PM" src="https://user-images.githubusercontent.com/62077/105921070-3b32b980-5fed-11eb-8428-3b6ce8767ebc.png">

**Comment by fbogsany** [comment]
> This happens with and without prometheus instrumentation enabled. So may or may not be related to #352

What other gems do you have loaded (that may contain instrumentation)?

**Comment by treyhyde** [comment]
raindrops, prometheus exporter, maybe something in unicorn hooks?   Certainly nothing intentional.

**Comment by fbogsany** [comment]
This is the same problem as #352. Prometheus exporter uses `alias_method` to patch methods in `Redis::Client` and other classes: https://github.com/discourse/prometheus_exporter/blob/master/lib/prometheus_exporter/instrumentation/method_profiler.rb

**Comment by fbogsany** [comment]
Hmm, you mentioned that the problem occurred even with Prometheus exporter instrumentation disabled. Can you remove Prometheus exporter altogether to confirm whether that's the problem?

I looked through Raindrops and couldn't find anything suspicious.

**Comment by treyhyde** [comment]
Right, full on removing the prometheus_exporter gem from the bundle does the trick.

<img width="1455" alt="Screen Shot 2021-02-01 at 9 28 55 AM" src="https://user-images.githubusercontent.com/62077/106495028-018c0380-6470-11eb-9270-d7fa970d96d5.png">

**Comment by Piioo** [comment]
We have the same problem after updated from 0.19.3 to 0.19.4

After a downgrade to 0.19.3 it works again

**Comment by and0x000** [comment]
It appears that I have stumbled upon the same issue.

Rails 7, Ruby 3, unicorn

gems in use that seem related to this:

```ruby
gem 'sentry-opentelemetry'
gem 'sentry-rails'
gem 'sentry-ruby'

gem 'opentelemetry-instrumentation-active_record'
gem 'opentelemetry-instrumentation-active_support'
gem 'opentelemetry-instrumentation-concurrent_ruby'
gem 'opentelemetry-instrumentation-net_http'
gem 'opentelemetry-instrumentation-pg'
gem 'opentelemetry-instrumentation-rack'
gem 'opentelemetry-instrumentation-rails'
gem 'opentelemetry-instrumentation-rake'
gem 'opentelemetry-instrumentation-redis'
gem 'opentelemetry-sdk'

gem 'prometheus_exporter'
```

All of them on the respective latest version at this point in time.

Problems when I have

```ruby
  Rails.application.middleware.use PrometheusExporter::Middleware
```

in combination with the

```
gem 'opentelemetry-instrumentation-pg'
```

If I comment out one of them, the exception is gone. If both are in, the app throws a `SystemStackError`.
