### ISSUE TITLE
Opentelemetry SDK - SimpleSpanProcessor error - undefined method export

### ISSUE THREAD

**Issue by mat-rumian** [open-telemetry/opentelemetry-ruby#595]
**Description:**
Undefined method export for SimpleSpanProcessor appears.

**Steps:**
I've used [example application](https://github.com/JetBrains/sample_rails_app). 
1. Add in Gemfile:
  gem 'opentelemetry-sdk', '0.13.1'
  gem 'opentelemetry-instrumentation-all', '0.13.0'
  gem 'opentelemetry-exporter-otlp', '0.13.0'
2. Add in config/environment.rb
```
OpenTelemetry::SDK.configure do |c|
  c.use_all
  c.add_span_processor(
    OpenTelemetry::SDK::Trace::Export::SimpleSpanProcessor.new(
       exporter: OpenTelemetry::Exporter::OTLP::Exporter.new()
    )
  )
end
```
3. Run the [application](https://github.com/JetBrains/sample_rails_app#getting-started) 

**Result:**
```
E, [2021-02-02T19:59:28.444907 #46573] ERROR -- : OpenTelemetry error: /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/opentelemetry-sdk-0.13.1/lib/opentelemetry/sdk/trace/export/simple_span_processor.rb:58:in `on_finish' - /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/opentelemetry-sdk-0.13.1/lib/opentelemetry/sdk/trace/multi_span_processor.rb:43:in `block in on_finish' - /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/opentelemetry-sdk-0.13.1/lib/opentelemetry/sdk/trace/multi_span_processor.rb:43:in `each' - /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/opentelemetry-sdk-0.13.1/lib/opentelemetry/sdk/trace/multi_span_processor.rb:43:in `on_finish' - /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/opentelemetry-sdk-0.13.1/lib/opentelemetry/sdk/trace/span.rb:211:in `finish' - /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/opentelemetry-api-0.13.0/lib/opentelemetry/trace/tracer.rb:36:in `in_span' - /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/opentelemetry-instrumentation-rack-0.13.0/lib/opentelemetry/instrumentation/rack/middlewares/tracer_middleware.rb:63:in `block in call' - /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/opentelemetry-api-0.13.0/lib/opentelemetry/context.rb:46:in `with_current' - /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/opentelemetry-instrumentation-rack-0.13.0/lib/opentelemetry/instrumentation/rack/middlewares/tracer_middleware.rb:60:in `call' - /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/request_id.rb:27:in `call' - /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call' - /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call' - /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call' - /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/executor.rb:14:in `call' - /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/static.rb:126:in `call' - /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call' - /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/host_authorization.rb:77:in `call' - /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/webpacker-4.0.7/lib/webpacker/dev_server_proxy.rb:29:in `perform_request' - /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call' - /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/engine.rb:526:in `call' - /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/puma-3.12.2/lib/puma/configuration.rb:227:in `call' - /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/puma-3.12.2/lib/puma/server.rb:674:in `handle_request' - /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/puma-3.12.2/lib/puma/server.rb:476:in `process_client' - /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/puma-3.12.2/lib/puma/server.rb:334:in `block in run' - /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/puma-3.12.2/lib/puma/thread_pool.rb:135:in `block in spawn_thread' - undefined method `export' for #<Hash:0x00007fb8fb3a7f08>
```

**Environment:**
- 'opentelemetry-sdk', '0.13.1'
- 'opentelemetry-instrumentation-all', '0.13.0'
- 'opentelemetry-exporter-otlp', '0.13.0'
- OT Collector in version '0.19.0'

**Comment by robertlaurin** [comment]
If you look at the [`initialize` method](https://github.com/open-telemetry/opentelemetry-ruby/blob/opentelemetry-sdk/v0.13.1/sdk/lib/opentelemetry/sdk/trace/export/simple_span_processor.rb#L31-L33) for the `SimpleSpanProcessor` you'll see that it doesn't specify a keyword argument `exporter`.

In your config block you're passing in `exporter: OpenTelemetry::Exporter::OTLP::Exporter.new()` which is be implicitly passed as a hash.

See in the [`on_finish` method](https://github.com/open-telemetry/opentelemetry-ruby/blob/opentelemetry-sdk/v0.13.1/sdk/lib/opentelemetry/sdk/trace/export/simple_span_processor.rb#L58), that's why your stack trace is raising an error `undefined method export for #<Hash:0x00007fb8fb3a7f08>` because it's trying to call export against the hash you passed in.

```
# E, [2021-02-02T19:59:28.444907 #46573] ERROR -- : OpenTelemetry error: 
#  - /Users/mrumian/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/opentelemetry-sdk-0.13.1/lib/opentelemetry/sdk/trace/export/simple_span_processor.rb:58:in `on_finish'
...
#  undefined method `export' for #<Hash:0x00007fb8fb3a7f08>
```

You can test and see for yourself with this small snippet of code, if you prepend `OpenTelemetry::Exporter::OTLP::Exporter.new` with `exporter` you'll get a similar stack trace. 
```rb
require 'opentelemetry/exporter/otlp'
require 'opentelemetry/sdk'

OpenTelemetry::SDK.configure do |c|
  c.add_span_processor(
    OpenTelemetry::SDK::Trace::Export::SimpleSpanProcessor.new(
      OpenTelemetry::Exporter::OTLP::Exporter.new
    )
  )
end

tracer = OpenTelemetry.tracer_provider.tracer('demo', '123')

tracer.in_span('#puts') do
  puts "hello"
end
```

It's worth mentioning that you typically do **not** want to be using the `SimpleSpanProcessor` in a production environment.  https://github.com/open-telemetry/opentelemetry-ruby/blob/02549df1103117a5670e06f3f929cf847390e5e3/sdk/lib/opentelemetry/sdk/trace/export/simple_span_processor.rb#L15-L19

**Comment by fhwang** [comment]
In the interests of lowering the barrier to entry, how would we feel about validating the method signatures of the `exporter` argument in processor instantiation? A clear error might save a lot of engineer cycles.

**Comment by fbogsany** [comment]
> In the interests of lowering the barrier to entry, how would we feel about validating the method signatures of the `exporter` argument in processor instantiation? A clear error might save a lot of engineer cycles.

Sounds like a good idea 👍

**Comment by mat-rumian** [comment]
Thank you very much! :)
