### ISSUE TITLE
Problem with running Rails instrumentation example

### ISSUE THREAD

**Issue by rishm069** [open-telemetry/opentelemetry-ruby#700]
I've encountered the following issue when tried to run the example from [here](https://github.com/open-telemetry/opentelemetry-ruby/blob/main/instrumentation/rails/example/trace_request_demonstration.ru):

```
$ rackup trace_request_demonstration.ru 
Fetching https://github.com/rails/rails.git
fatal: Needed a single revision
Traceback (most recent call last):
	46: from /home/user/.asdf/installs/ruby/2.7.1/bin/rackup:23:in `<main>'
	45: from /home/user/.asdf/installs/ruby/2.7.1/bin/rackup:23:in `load'
	44: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/bin/rackup:5:in `<top (required)>'
	43: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:168:in `start'
	42: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
	41: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
	40: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
	39: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
	38: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
	37: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	36: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
	35: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
	34: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
	33: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
	32: from /home/rinat/opentelemetry-test/opentelemetry-ruby/instrumentation/rails/example/trace_request_demonstration.ru:9:in `block in <main>'
	31: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/inline.rb:54:in `gemfile'
	30: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/settings.rb:124:in `temporary'
	29: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/inline.rb:61:in `block in gemfile'
	28: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/settings.rb:124:in `temporary'
	27: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/inline.rb:62:in `block (2 levels) in gemfile'
	26: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/installer.rb:25:in `install'
	25: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/installer.rb:73:in `run'
	24: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/process_lock.rb:9:in `lock'
	23: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/process_lock.rb:9:in `open'
	22: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/process_lock.rb:12:in `block in lock'
	21: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/installer.rb:84:in `block in run'
	20: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/installer.rb:303:in `resolve_if_needed'
	19: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/definition.rb:158:in `resolve_remotely!'
	18: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/definition.rb:170:in `specs'
	17: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/definition.rb:247:in `resolve'
	16: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/definition.rb:750:in `converge_locked_specs'
	15: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/definition.rb:750:in `each'
	14: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/definition.rb:764:in `block in converge_locked_specs'
	13: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/source/git.rb:163:in `specs'
	12: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/source/git.rb:93:in `install_path'
	11: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/source/git.rb:226:in `revision'
	10: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:68:in `revision'
	 9: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:198:in `find_local_revision'
	 8: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:240:in `allowed_in_path'
	 7: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:236:in `in_path'
	 6: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/shared_helpers.rb:51:in `chdir'
	 5: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/shared_helpers.rb:51:in `synchronize'
	 4: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/shared_helpers.rb:52:in `block in chdir'
	 3: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/shared_helpers.rb:52:in `chdir'
	 2: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:240:in `block in allowed_in_path'
	 1: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:199:in `block in find_local_revision'
/home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:181:in `git': Git error: command `git rev-parse --verify master` in directory /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/cache/bundler/git/rails-fcf0202857b07db1a0f6220dae5ca99319ca0f32 has failed. (Bundler::Source::Git::GitCommandError)
If this error persists you could try removing the cache directory '/home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/cache/bundler/git/rails-fcf0202857b07db1a0f6220dae5ca99319ca0f32'
	37: from /home/user/.asdf/installs/ruby/2.7.1/bin/rackup:23:in `<main>'
	36: from /home/user/.asdf/installs/ruby/2.7.1/bin/rackup:23:in `load'
	35: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/bin/rackup:5:in `<top (required)>'
	34: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:168:in `start'
	33: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
	32: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
	31: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
	30: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
	29: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
	28: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	27: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
	26: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
	25: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
	24: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
	23: from /home/rinat/opentelemetry-test/opentelemetry-ruby/instrumentation/rails/example/trace_request_demonstration.ru:9:in `block in <main>'
	22: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/inline.rb:54:in `gemfile'
	21: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/settings.rb:124:in `temporary'
	20: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/inline.rb:61:in `block in gemfile'
	19: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/settings.rb:124:in `temporary'
	18: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/inline.rb:62:in `block (2 levels) in gemfile'
	17: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/installer.rb:25:in `install'
	16: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/installer.rb:73:in `run'
	15: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/process_lock.rb:9:in `lock'
	14: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/process_lock.rb:9:in `open'
	13: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/process_lock.rb:12:in `block in lock'
	12: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/installer.rb:84:in `block in run'
	11: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/installer.rb:303:in `resolve_if_needed'
	10: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/definition.rb:158:in `resolve_remotely!'
	 9: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/definition.rb:170:in `specs'
	 8: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/definition.rb:247:in `resolve'
	 7: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/definition.rb:750:in `converge_locked_specs'
	 6: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/definition.rb:750:in `each'
	 5: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/definition.rb:764:in `block in converge_locked_specs'
	 4: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/source/git.rb:163:in `specs'
	 3: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/source/git.rb:93:in `install_path'
	 2: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/source/git.rb:226:in `revision'
	 1: from /home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:67:in `revision'
/home/user/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/source/git/git_proxy.rb:70:in `rescue in revision': Git error: command `git rev-parse --verify master` in directory /home/rinat/opentelemetry-test/opentelemetry-ruby has failed. (Bundler::Source::Git::MissingGitRevisionError)
Revision master does not exist in the repository https://github.com/rails/rails.git. Maybe you misspelled it?
If this error persists you could try removing the cache directory '/home/user/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/cache/bundler/git/rails-fcf0202857b07db1a0f6220dae5ca99319ca0f32'
```
I have been able to fix this by specifying branch on [this line](https://github.com/open-telemetry/opentelemetry-ruby/blob/main/instrumentation/rails/example/trace_request_demonstration.ru#L14):
```ruby
  gem 'rails', github: 'rails/rails', branch: 'main'
```

**Comment by ahayworth** [comment]
Hi @rishm069 - thanks for the report! I've opened https://github.com/open-telemetry/opentelemetry-ruby/pull/704 to fix this (by just using the version of rails released to rubygems, rather than building it from source).
