### ISSUE TITLE
Rescue OpenSSL::SSL::SSLError

### ISSUE THREAD

**Issue by parkr** [open-telemetry/opentelemetry-ruby#883]
According to the spec:

> The SDK MUST NOT throw unhandled exceptions for errors in their own operations. For example, an exporter should not throw an exception when it cannot reach the endpoint to which it sends telemetry data.

Unfortunately, we encountered an exception with v0.16.0 and Ruby 3.0.1 which resulted in an HTTP 500 for our service:

```text
OpenSSL::SSL::SSLError
SSL_read: decryption failed or bad record mac
/usr/local/lib/ruby/3.0.0/openssl/buffering.rb:205:in `sysread_nonblock'
/usr/local/lib/ruby/3.0.0/openssl/buffering.rb:205:in `read_nonblock'
/usr/local/lib/ruby/3.0.0/net/protocol.rb:212:in `rbuf_fill'
/usr/local/lib/ruby/3.0.0/net/protocol.rb:193:in `readuntil'
/usr/local/lib/ruby/3.0.0/net/protocol.rb:203:in `readline'
/usr/local/lib/ruby/3.0.0/net/http/response.rb:42:in `read_status_line'
/usr/local/lib/ruby/3.0.0/net/http/response.rb:31:in `read_new'
/usr/local/lib/ruby/3.0.0/net/http.rb:1557:in `block in transport_request'
/usr/local/lib/ruby/3.0.0/net/http.rb:1548:in `catch'
/usr/local/lib/ruby/3.0.0/net/http.rb:1548:in `transport_request'
/usr/local/lib/ruby/3.0.0/net/http.rb:1521:in `request'
/usr/local/bundle/gems/opentelemetry-instrumentation-net_http-0.16.0/lib/opentelemetry/instrumentation/net/http/patches/instrumentation.rb:35:in `block in request'
/usr/local/bundle/gems/opentelemetry-api-0.16.0/lib/opentelemetry/trace/tracer.rb:29:in `block in in_span'
/usr/local/bundle/gems/opentelemetry-api-0.16.0/lib/opentelemetry/trace.rb:82:in `block in with_span'
/usr/local/bundle/gems/opentelemetry-api-0.16.0/lib/opentelemetry/context.rb:62:in `with_value'
/usr/local/bundle/gems/opentelemetry-api-0.16.0/lib/opentelemetry/trace.rb:82:in `with_span'
/usr/local/bundle/gems/opentelemetry-api-0.16.0/lib/opentelemetry/trace/tracer.rb:29:in `in_span'
/usr/local/bundle/gems/opentelemetry-instrumentation-net_http-0.16.0/lib/opentelemetry/instrumentation/net/http/patches/instrumentation.rb:22:in `request'
/usr/local/bundle/gems/opentelemetry-exporter-otlp-0.16.0/lib/opentelemetry/exporter/otlp/exporter.rb:161:in `block (2 levels) in send_bytes'
/usr/local/bundle/gems/opentelemetry-exporter-otlp-0.16.0/lib/opentelemetry/exporter/otlp/exporter.rb:208:in `measure_request_duration'
/usr/local/bundle/gems/opentelemetry-exporter-otlp-0.16.0/lib/opentelemetry/exporter/otlp/exporter.rb:161:in `block in send_bytes'
/usr/local/bundle/gems/opentelemetry-exporter-otlp-0.16.0/lib/opentelemetry/exporter/otlp/exporter.rb:136:in `block in around_request'
/usr/local/bundle/gems/opentelemetry-common-0.16.0/lib/opentelemetry/common/utilities.rb:60:in `block in untraced'
/usr/local/bundle/gems/opentelemetry-api-0.16.0/lib/opentelemetry/trace.rb:82:in `block in with_span'
/usr/local/bundle/gems/opentelemetry-api-0.16.0/lib/opentelemetry/context.rb:62:in `with_value'
/usr/local/bundle/gems/opentelemetry-api-0.16.0/lib/opentelemetry/trace.rb:82:in `with_span'
/usr/local/bundle/gems/opentelemetry-common-0.16.0/lib/opentelemetry/common/utilities.rb:60:in `untraced'
/usr/local/bundle/gems/opentelemetry-exporter-otlp-0.16.0/lib/opentelemetry/exporter/otlp/exporter.rb:136:in `around_request'
/usr/local/bundle/gems/opentelemetry-exporter-otlp-0.16.0/lib/opentelemetry/exporter/otlp/exporter.rb:143:in `send_bytes'
/usr/local/bundle/gems/opentelemetry-exporter-otlp-0.16.0/lib/opentelemetry/exporter/otlp/exporter.rb:76:in `export'
/usr/local/bundle/gems/opentelemetry-sdk-0.16.0/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb:186:in `block in export_batch'
/usr/local/bundle/gems/opentelemetry-sdk-0.16.0/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb:186:in `synchronize'
/usr/local/bundle/gems/opentelemetry-sdk-0.16.0/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb:186:in `export_batch'
/usr/local/bundle/gems/opentelemetry-sdk-0.16.0/lib/opentelemetry/sdk/trace/export/batch_span_processor.rb:113:in `force_flush'
/usr/local/bundle/gems/opentelemetry-sdk-0.16.0/lib/opentelemetry/sdk/trace/tracer_provider.rb:81:in `block in force_flush'
/usr/local/bundle/gems/opentelemetry-sdk-0.16.0/lib/opentelemetry/sdk/trace/tracer_provider.rb:78:in `synchronize'
/usr/local/bundle/gems/opentelemetry-sdk-0.16.0/lib/opentelemetry/sdk/trace/tracer_provider.rb:78:in `force_flush'
```

Chatting with @arielvalentin, it seems like we might need to add OpenSSL errors to a list here: https://github.com/open-telemetry/opentelemetry-ruby/blob/980f0e454c59e822de439635ee513e2bcdf820b8/exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb#L199-L211

**Comment by robbkidd** [comment]
Today's SIG talked about this issue in overtime and those present agreed that adding another `rescue` to this chain of rescues for OpenSSL exceptions makes sense. It's the best way today to diagnose errors at the OTel SDK level while also not throwing exceptions into the instrumented application process.

**Comment by parkr** [comment]
Thanks, all! 🎉
